version: '3.9'
services:
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    environment:
      CUR_APPLICATION: blue

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: mind_travel
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  blue:
    build: .
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mind_travel
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis

  green:
    build: .
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mind_travel
      SERVER_PORT: 8081
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - redis

volumes:
  db_data:
  redis_data: