spring:
  datasource:
    url: jdbc:mysql://localhost/mind_travel
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  messages:
    basename: fcm-messages
    encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      format_sql: true
  profiles:
    include: oauth,kakao
  data:
    redis:
      host: redis
      port: 6379
logging.level:
  org.hibernate.SQL: debug
