spring:
  datasource:
    url: jdbc:mysql://localhost/mind_travel
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      format_sql: true
  profiles:
    include: oauth
logging.level:
  org.hibernate.SQL: debug
